services:
  frontend:
    image: portfolio-website-frontend
    build:
      context: ./frontend
      args:
        BACKEND_URL: http://localhost:8081/
    links:
      - smtp-mock
    ports:
      - "8080:8080"
  smtp-mock:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"
