version: '3.9'

services:
  next-app:
    image: portfolio-website-next-app
    build:
      context: ./next-app
    ports:
      - "8080:3000"
  smtp-mock:
    restart: on-failure
    image: dockage/mailcatcher:0.8.2
    ports:
      - "1080:1080"
      - "1025:1025"
