[package]
name = "portfolio-website-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
axum = "0.7.5"
lettre = "0.11.7"
