name: Deploy Production Frontend
on:
  push:
    branches: ["trunk"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ./frontend
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ./frontend/.next/cache
          key: ${{ runner.os }}-github-pages-${{ hashFiles('./frontend/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-github-pages-${{ hashFiles('./frontend/package-lock.json') }}-
      - name: Install dependencies
        run: npm ci
      - name: Build frontend
        env:
          NEXT_PUBLIC_BACKEND_URL: https://api.${{ vars.SERVER_BASE_DOMAIN }}
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build
      - name: Debugging
        run: |
          ls -al ./
          ls -al ./.next
      - name: Archive artifact
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory ./out \
            -cvf "$RUNNER_TEMP/github-pages.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/github-pages.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Frontend to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
