name: Deploy Production Frontend
on:
  push:
    branches: ["trunk"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    outputs:
      artifact_id: ${{ steps.upload-artifact.outputs.artifact_id }}

    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          key: ${{ runner.os }}-github-pages-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-github-pages-${{ hashFiles('**/package-lock.json') }}-
      - name: Node modules install
        run: npm ci --omit=dev
      # backend URL definition *****
      - name: Next build
        run: npm run build
      - name: Archive artifact
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory ./out \
            -cvf "$RUNNER_TEMP/github-pages.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/github-pages.tar
          retention-days: 1
          if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy Frontend to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
