name: Deploy Branch
on:
  workflow_dispatch:

jobs:
  frontend-docker:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v4
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Build Docker image"
        run: "docker build ./ -t portfolio-website-next-app:${{ github.sha }}"
