name: Deploy
on:
  push:
    branches:
      - 'trunk'

jobs:
  next-app-docker:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./next-app

    steps:
      - name: "Repo checkout"
        uses: actions/checkout@v4
      - name: "Setup node"
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: "Test curl"
        run: curl https://images.unsplash.com/photo-1597138768744-9f97be8cdd64 --output test.png
      - name: "Build Docker image"
        run: "docker build ./ -t portfolio-website-next-app:${{ github.sha }}"
